import { Container } from "@/components/Container";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"], // you can also add "latin-ext"
  weight: ["400", "500", "600", "700"], // optional
  variable: "--font-inter", // optional (for CSS variables)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div
        className={`${inter.className} font-sans h-screen w-full flex justify-center bg-black antialiased`}
      >
        <Container>
        {children}
        </Container>
      </div>
  );
}
